baseurl = "/"
languageCode = "en-us"
title = "My personal blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/DanaeMirel"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/DanaeMa76161560"
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/danaemartinez/"
[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    #favicon = "favicon.ico"
    favicon = "Danae.ico"
    
    [params.logo]
    url = "Danae.jpeg"
    width = 50
    height = 50
    alt = "Logo"

