---
title: Generate energy
author: Danae Martinez
date: '2020-09-09'
slug: generate-energy
categories: []
tags: []
---

You will notice that energy isn't just physical, mental alertness mattes too. So does positive emotion. Energy is significantly related to productivity. You can increase your energy and overall performance with just a few simple practices:

1. *Practice one*: **Release tension, set intention**

Shift from one activity to the next, consciously setting an intention. This means, 
- think about what you want to feel and achieve in the next activity. 
- what energy do you want to bring into this new activity? 
- how can you do this next activity with excellence ? 
- how can you enjoy the process? 

Another way to release the tension is to practice the [release meditation tecnique](https://www.youtube.com/watch?v=v2mY36Ho1Sk&ab_channel=Brendon.com).

2. *Practice two* : **Bring the joy**

Positive emotion, in general, is one of the greatest predictors of the good life-high energy and high performance. 

Remember that you can choose your feelings. Events are neutral, you decide how you interpret them. Your automatic emotions don’t have to be in charge, you are in charge of how you feel. 

Consciously direct your toughs and behaviors to generate positive emotions. More specifically, you can: 

- anticipate positive outcomes from your actions,
- think about how do yo want to feel and practice visualizations that generates those feelings, 
- imagine stressful situations and how your best self might handle them,
- seek to insert appreciation, surprise, wonder and challenge into your day,
- steer social interactions towards positive emotions and experiences,
- reflect regularly on all that you are grateful for.

3. *Practice three* : **Optimize heath**

You need to exercise. A lot! Especially if you care about your mental performance. You already know the basics of heath optimization, but it is important to engage to adopt those habits and make them your priority. 

- Sleep 
- Drink water
- Exercise 
- Eat well 

The next post gives more details and some advise in order to deep into those basics. 


