---
title: 'What is cloud computing? '
author: Danae Martinez
date: '2020-09-22'
slug: what-is-cloud-computing
categories: []
tags: []
---


## Understanding the cloud

You may have heard of the cloud in the context of storing your photos and videos online, but cloud computing is more than that. It is part of a business model that is becoming increasingly popular with more and more companies moving their workloads to the cloud.

### Cloud vs. on-premise

The cloud is transforming the way organizations use computer services. Where in the past you had to own local servers and systems, in the cloud they are managed by an external provider that charges you for the use.

### Primary cloud services

Cloud providers like AWS, Microsoft Azure, and Google Cloud offer a wide variety of services. The three basic ones, which you will be able to find for every cloud provider, are:

- Compute
- Storage
- Databases

### Key characteristics

Cloud computing services provide more possibilities for organizations all over the world. These services share certain characteristics that make them very powerful. 

### Outsourcing IT services

Cloud computing is offered in three different service models each satisfying a unique set of business requirements. It's important to understand what each model offers. There are three main service models:

- Infrastructure as a Service (IaaS) - offers cloud infrastructure
- Platform as a Service (PaaS) - offers infrastructure and software for application development
- Software as a Service (SaaS) - offers ready-to-use applications in the cloud. Over the past years more and more functionality is being abstracted away from the end user, and offered as a cloud service package.
