---
title: 'Raise necessity '
author: Danae Martinez
date: '2019-09-19'
slug: raise-necessity
categories: []
tags: []
---

One of the most powerful drivers of human motivation and excellence is *performance necessity*. Necessity is the emotional drive that makes grate performance a must instead of a preference. Unlike weaker desires that make you want to do something, necessity *demands* you that you take action. Necessity inspires a higher sense of motivation that usual because personal identity is engaged, creating a sense of urgency to act.       

You most get more emotionally committed to what you are doing, and reach that point where success is not just an occasional preference but a soul-deep necessity.

The Four forces of necessity are identity, obsession, duty and urgency. 

- *Identity* : personal standards of excellence. Those people care more about excellence and thus put more effort into their activities that others do. 

One tip to increase your personal standards is to set new standards, self-monitoring more frequently and learn to become comfortable with taking a hard look at your own performance. 

See yourself as a person who loves challenge and go for the big dreams. You are stronger than you think, and the future holds good things for you.   

- *Obsession* : when I say obsession here, I don't mean the kind of unhealthy obsession, but, let's be honest, a little recklessness is required for the extraordinary to happen. It is reckless to try something that has never been done, to move against convention, to begin before all conditions are good and preparations are perfect.   

The moment you know that something has transcended being a passion and has become an obsession is when than something gets tied to your identity. 

- *Social duty* : this is an external force, coming from the sense of obligation and purpose. The duties that drives performance ca be explained best by the truth that we will often do more for others that for ourselves.  


- *Urgency* : real deadlines 

Some practices that migth help you raise necessity are

1. Know who needs your A game 

2. Affirm the why

3. Level up your squad 
