---
title: Persuading Others: Overcome resistance
author: Danae Martinez
date: '2021-02-12'
slug: overcome-resistance
categories:
  - leadership
tags:
  - communication
---

## Index 
1. Understand resisters
2. Verbal and nonverbal consistency
3. Acknowledge their arguments first

Even a carefully thought-out proposal for an idea can meet with resistance. But pressing your case won't work. Instead, apply powerful practices to break down the barriers and turn resisters into receptive listeners.

## 1. Understand resisters

Because of their unique interests, emotions, and values, many of your listeners will have already rejected your idea even before they've heard your case.

Your job is to make resisters receptive to your idea. To do so, you need to understand their **interests**, **emotions**, and **values**. Then you can adapt your persuasion strategies accordingly.

### 1.1 Interests

1. If you think that self-interest may be driving a listener’s resistance to your idea, craft a message that appeals to that interest.

2. Sometimes, there are several interests involved in a person’s resistance to an idea. If you’re not confident that you can appeal to what seems to be the key interest, try appealing to another interest the person has.

### 1.2 Emotions

Consider emotions that may be triggering resistance. Most resistance springs from two emotions:

1. **Fear**. Resisters don't like your idea because they think it could have negative consequences for them. Or they’re worried it could hurt other people or causes they support. To ease fear, provide as much evidence as possible that the negative consequences people are concerned about won’t happen or that your idea’s benefits will outweigh any negative consequences.

2. **Distrust**. A person doesn't like you as a person or what you represent, for some reason. He or she might have been treated badly by you, by someone in your position, or by someone like you in the past. To address distrust, treat resisters courteously and listen closely to their concerns. By listening, you demonstrate that you understand and value these individuals and appreciate their concerns. When people feel heard and valued, they trust you more and are thus more open to considering your ideas.


The following listening techniques can help you reduce distrust in your listeners:

- **Paraphrase**. Restate the resister's points in your own words. Then say something like *"Am I understanding you correctly?"* This prompts your listener to respond with comments such as, *"Well, yeah, that's what I'm saying."* By getting the person to agree with you—even in this small way—you establish common ground, which fosters receptivity to your ideas.

- **Clarify the vital issues**. Identify the resister's primary concerns. You’ll establish even more understanding and agreement. And you’ll show that you're capable of sorting out the vital issues. This can further wear down resistance.

### 1.3 Values

If you show how your idea supports a core value held by a resister, you can boost the chances of overcoming his or her resistance.

## Verbal and nonverbal consistency

When you're discussing your idea with a resister, convey confidence in what you're proposing. Make sure your posture is upright and your gestures assertive. Make frequent eye contact with the other person. And speak in a confident tone of voice but keep the volume moderate.

### Tips for speaking with confidence

1. **Control your speaking pace**. Speak slowly enough for listeners to follow but quickly enough to sustain their interest.

2. **Use a low-pitched voice**. Many people interpret a low-pitched voice as authoritative and influential. Likewise, completing a sentence with a downward inflection-a lowering of pitch-communicates confidence and certainty.

3. **Control loudness**. Speak loudly enough to be heard but not so loudly as to irritate or offend listeners. Increase the volume of your voice a bit when you want to emphasize important words and phrases.

4. **Be articulate**. Clearly articulate words and phrases to convey confidence and competence.

5. **Use pauses for impact**. Pause just before making a point you want to emphasize-and maintain eye contact with your listeners during the pause.

Avoid looking defensive by remembering a few simple rules.

1. **Pause and prepare**. When faced with an unexpected or confrontational question, stop for a second. Take a breath. And think about what was just asked.
2. If you’re unclear about any part of the question, calmly **ask for clarification**.
3. **Align with the question**. The goal is to quickly and conversationally make the questioner feel heard and understood, which helps defuse the tension in the room.
4. Once you’ve aligned with the facts or emotions, **don’t transition** to your explanation **by using** the words **“but” or “however”**. Instead, simply pause before offering your explanation.
5. Then, keep it **brief** and on point. Be aware of your voice and body language. Keep the mood conversational. 


## Acknowledge their arguments first

If you suspect ahead of time that you'll encounter resistance from listeners, prepare a two-sided argument: theirs and yours.

When you present your idea to them, acknowledge their arguments first. You'll disarm them by removing the opportunity for them to oppose you. Without this opportunity, they'll be more open to discussing your idea and listening to the solution you propose.

Present your argument second. Clearly show how the idea you’re proposing provides a better solution than your opponents' does. But also show how you've incorporated resisters' ideas, interests, values, and concerns into your solution.


## References: 

[Persuading Others](https://edls.myhbp.org/hmm12/content/persuading_others/landingpage.html)
