---
title: Activate persuasion triggers
author: Danae Martinez
date: '2021-02-19'
slug: persuasion-triggers
categories:
  - leadership
tags:
  - communication
---

Consider using a select few "triggers," or mental shortcuts, to streamline the persuasion process. Each of the eight persuasion triggers — contrast, liking, relationship, reciprocity, social proof, commitment and consistency, authority, and scarcity — can make all the difference if properly, and ethically leveraged.

### Contrast

When people make decisions, they often look for a benchmark on which to base their choice.

To activate the “contrast” trigger, create a benchmark to "anchor" the judgments of the person you need to persuade. Many salespeople do this by first showing the most expensive item in a product line. This makes a midpriced item seem much more affordable.

### Liking

People tend to accept the ideas of people they like. Liking arises when people feel esteemed by another person and when they share something in common with him or her. A manager might choose an inferior deal from a supplier's representative over a better deal, just because he likes the first rep and they share a common interest in football.

To activate the "liking" trigger, create bonds with others by informally discovering common interests such as music, children, pets, or sports. Demonstrate your liking for others by paying genuine compliments and making positive statements about their ideas, solutions, abilities, and qualities.

### Relationship

People are more likely to adopt a proposed idea if the individual advocating the idea is someone with whom they have a relationship—even if it's just something in common—and the person makes them aware of that relationship. In a study conducted on a college campus, charity solicitors more than doubled their success by preceding a donation request with these five words: "I'm a student here, too."

To activate the "relationship" trigger, point out the length of your connection with the person you want to persuade. Note things like "We've been at this together for three years." Identify shared interests, experiences, and goals. Sprinkle your messages with words like "we," "our," and "us."

### Reciprocity

People feel a deep urge to repay favors in kind. To activate the “reciprocity” trigger, give before you ask for something. In considering what to give, look for solutions that meet other individuals' interests and needs.

### Social proof

People are more likely to follow another person's lead if what that person is advocating is popular, standard practice, or part of a trend. Just look at the widespread use of celebrity endorsements in advertising.

To activate the "social proof" trigger, make a connection—yourself, your organization, your product—to individuals and organizations admired by those you're seeking to persuade.

### Commitment and consistency

People are more likely to embrace a proposal if they've committed to it through their own choice and have done so publicly; for example, by announcing it or in writing. Researchers noted that nine out of 10 residents of an apartment complex who signed a petition supporting a new recreation center later donated money to the cause.

To activate the “commitment and consistency” trigger, get others' voluntary, public, and documented commitment.

### Scarcity

To activate the “scarcity” trigger, convince your listeners that they’re being offered something rare.


## References: 

[Persuading Others](https://edls.myhbp.org/hmm12/content/persuading_others/landingpage.html)